name: grow_more
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  simple_animations: ^2.2.1
  passwordfield: ^0.0.5
  neumorphic: ^0.3.0
  provider: ^3.1.1
  usage: ^3.4.1
  email_validator: ^1.0.4
  flutter_spinkit: ^4.1.2+1
  json_annotation: ^3.0.1
  intro_slider: ^2.3.1
  uuid: 2.0.4
  get_it: ^4.0.2
  expandable: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.8.1
  json_serializable: ^3.3.0
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/dashboardImages/plant.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/loginScreenImages/
    - assets/images/dashboardImages/
    - assets/images/

